name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy Frontend
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd /root/nibbleFrontend
            git pull origin main
            npm install
            npm run build
            # Stop any existing PM2 instance safely
            pm2 delete nextjs || true

            # Start fresh PM2 instance
            pm2 start npm --name "nextjs" -- start

            # Save PM2 process list for reboot
            pm2 save
          EOF
